
IF OBJECT_ID('PERSONS_UPLOAD_DATA', 'P') IS NOT NULL
  DROP PROCEDURE PERSONS_UPLOAD_DATA;
GO

CREATE PROCEDURE PERSONS_UPLOAD_DATA @VI_CSV_FILE_NAME VARCHAR(MAX), @VI_DIR_NAME VARCHAR(MAX), @VI_SEPARATOR VARCHAR(20)
AS

  DECLARE @V_ERROR_MESSAGE VARCHAR(4000);
  
  BEGIN
	

	BEGIN TRY
     -- READ CSV FILE  
     EXECUTE ('BULK INSERT PERSONS FROM ''' + @VI_DIR_NAME + '\' + @VI_CSV_FILE_NAME + ''' WITH (FIELDTERMINATOR = ''' + @VI_SEPARATOR + ''',ROWTERMINATOR = ''\N'')');
	END TRY
	BEGIN CATCH
     IF (ERROR_MESSAGE() LIKE '%' + 'OPERATING SYSTEM ERROR CODE' + '%')
	  BEGIN
		SET @V_ERROR_MESSAGE = ERROR_MESSAGE();
	  END
	 ELSE
		BEGIN
			SET @V_ERROR_MESSAGE = 'CSV FILE MUST CONTAIN COLUMNS IN SEQUENCE NO DATA IN CSV.';
		END
		INSERT INTO PERSONS_LOG (FILE_NAME, ISSUE_TYPE, ERROR_MESSAGE) VALUES (@VI_CSV_FILE_NAME, 'BULK', @V_ERROR_MESSAGE);
	END CATCH
	
	EXEC ('ALTER TABLE PERSONS ADD VALID VARCHAR(1) NOT NULL DEFAULT (''Y'')');

  END
GO
